@BASE_URL=http://localhost:3001

###
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "email": "test@gmail.com",
    "name": "jommm"
}

###
GET {{BASE_URL}}/users
Content-Type: application/json

###
GET {{BASE_URL}}
Content-Type: application/json
